blank_issues_enabled: false
contact_links:
  - name: Questions / Help
    url: https://github.com/suellenxstefany/netlify-supabase-resend-starter
    about: Please check the README first. If you still have an issue, open a Bug Report.
